import type { OrderingSchool, MealWeek, MenuCategory, Allergy, Meal } from '../types'

export const schools: OrderingSchool[] = [
  { id: 'sch-1', name: 'École Primaire Saint-Jean', city: 'Québec' },
  { id: 'sch-2', name: 'École des Sommets', city: 'Sainte-Foy' },
  { id: 'sch-3', name: 'École Marie-Clarac', city: 'Cap-Rouge' },
]

export const weeks: MealWeek[] = [
  { id: 'w-1', label: 'Sem. 1', startDate: '2026-05-25', endDate: '2026-05-29' },
  { id: 'w-2', label: 'Sem. 2', startDate: '2026-06-01', endDate: '2026-06-05' },
  { id: 'w-3', label: 'Sem. 3', startDate: '2026-06-08', endDate: '2026-06-12' },
  { id: 'w-4', label: 'Sem. 4', startDate: '2026-06-15', endDate: '2026-06-19' },
]

export const categories: MenuCategory[] = [
  { id: '', label: 'Tous', emoji: '🍽' },
  { id: 'cat-1', label: 'Plats', emoji: '🍖' },
  { id: 'cat-2', label: 'Entrées', emoji: '🥗' },
  { id: 'cat-3', label: 'Desserts', emoji: '🍰' },
  { id: 'cat-4', label: 'Boissons', emoji: '🥤' },
  { id: 'cat-5', label: 'Collations', emoji: '🍎' },
]

export const allergies: Allergy[] = [
  { id: 'a-1', label: 'Gluten',  emoji: '🌾', colorClass: 'bg-amber-100 text-amber-700 ring-amber-200' },
  { id: 'a-2', label: 'Lactose', emoji: '🥛', colorClass: 'bg-blue-100  text-blue-700  ring-blue-200'  },
  { id: 'a-3', label: 'Noix',    emoji: '🥜', colorClass: 'bg-orange-100 text-orange-700 ring-orange-200' },
  { id: 'a-4', label: 'Œufs',   emoji: '🥚', colorClass: 'bg-yellow-100 text-yellow-700 ring-yellow-200' },
  { id: 'a-5', label: 'Soja',    emoji: '🫘', colorClass: 'bg-green-100  text-green-700  ring-green-200'  },
  { id: 'a-6', label: 'Sésame', emoji: '🌰', colorClass: 'bg-stone-100  text-stone-600  ring-stone-200'  },
]

const ALL  = ['sch-1', 'sch-2', 'sch-3']
const W    = ['w-1', 'w-2', 'w-3', 'w-4']

// Day availability logic:
//   Plats      → 2 specific days (cafeteria rotation)
//   Entrées    → 2–3 days
//   Desserts / Boissons / Collations → all 5 days (always available)
const EVERY_DAY = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi']

export const meals: Meal[] = [
  // ── Plats (cat-1) — 3 unique meals per day, no meal repeats across days ──────

  // Lundi
  {
    id: 'm-1',
    name: 'Spaghetti Bolognaise',
    description: 'Sauce tomate mijotée maison avec viande hachée et légumes du jardin, servie avec des pâtes al dente.',
    price: 7.50,
    image: 'https://images.unsplash.com/photo-1555949258-aed28a8c8e97?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot'], allergyIds: ['a-1', 'a-2'],
    available: true, popular: true, isNew: false, calories: 520,
    availableDays: ['Lundi'],
  },
  {
    id: 'm-13',
    name: 'Lasagne Maison',
    description: 'Lasagnes gratinées à la bolognaise maison, couches de pâtes fraîches, béchamel onctueuse et fromage fondant.',
    price: 8.00,
    image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot'], allergyIds: ['a-1', 'a-2', 'a-4'],
    available: true, popular: true, isNew: false, calories: 540,
    availableDays: ['Lundi'],
  },
  {
    id: 'm-16',
    name: 'Bœuf Bourguignon',
    description: 'Mijoté de bœuf fondant au vin rouge, carottes, champignons et lardons, servi avec purée maison.',
    price: 9.00,
    image: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot'], allergyIds: ['a-2'],
    available: true, popular: true, isNew: false, calories: 580,
    availableDays: ['Lundi'],
  },

  // Mardi
  {
    id: 'm-4',
    name: 'Poulet Rôti & Légumes',
    description: 'Cuisse de poulet rôtie au four, accompagnée de légumes de saison grillés et de sauce aux herbes.',
    price: 8.50,
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c3?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot'], allergyIds: [],
    available: true, popular: true, isNew: false, calories: 480,
    availableDays: ['Mardi'],
  },
  {
    id: 'm-14',
    name: 'Wrap Poulet Grillé',
    description: 'Tortilla croustillante garnie de poulet grillé, légumes frais croquants et sauce yogourt-citron maison.',
    price: 6.75,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot'], allergyIds: ['a-1', 'a-2'],
    available: true, popular: false, isNew: true, calories: 420,
    availableDays: ['Mardi'],
  },
  {
    id: 'm-17',
    name: 'Filet de Saumon Citronné',
    description: 'Pavé de saumon grillé au citron et aneth, servi avec légumes vapeur et riz basmati.',
    price: 9.25,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot', 'gluten-free'], allergyIds: [],
    available: true, popular: false, isNew: true, calories: 440,
    availableDays: ['Mardi'],
  },

  // Mercredi
  {
    id: 'm-5',
    name: 'Sandwich Thon-Mayo',
    description: 'Pain de mie moelleux garni de thon, mayonnaise légère, tomates et laitue iceberg croustillante.',
    price: 5.75,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['cold'], allergyIds: ['a-1', 'a-4'],
    available: true, popular: false, isNew: false, calories: 380,
    availableDays: ['Mercredi'],
  },
  {
    id: 'm-18',
    name: 'Pizza Margherita',
    description: 'Pizza à pâte fine, sauce tomate maison, mozzarella fraîche et feuilles de basilic parfumé.',
    price: 7.25,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot', 'vegetarian'], allergyIds: ['a-1', 'a-2'],
    available: true, popular: true, isNew: false, calories: 500,
    availableDays: ['Mercredi'],
  },
  {
    id: 'm-19',
    name: 'Couscous Royal',
    description: 'Semoule fine aux légumes confits, pois chiches dorés, merguez grillée et bouillon épicé maison.',
    price: 8.25,
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot'], allergyIds: ['a-1'],
    available: true, popular: false, isNew: false, calories: 510,
    availableDays: ['Mercredi'],
  },

  // Jeudi
  {
    id: 'm-11',
    name: 'Quiche Lorraine',
    description: 'Quiche dorée à la crème, lardons fumés et fromage gruyère, servie tiède avec salade verte.',
    price: 7.00,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot'], allergyIds: ['a-1', 'a-2', 'a-4'],
    available: true, popular: false, isNew: false, calories: 560,
    availableDays: ['Jeudi'],
  },
  {
    id: 'm-15',
    name: 'Pâtes Primavera',
    description: 'Pâtes fraîches sautées aux légumes de saison — courgettes, tomates cerises, poivrons et basilic.',
    price: 6.50,
    image: 'https://images.unsplash.com/photo-1473093226555-0d10be5c3e27?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot', 'vegetarian'], allergyIds: ['a-1', 'a-2'],
    available: true, popular: false, isNew: false, calories: 410,
    availableDays: ['Jeudi'],
  },
  {
    id: 'm-20',
    name: 'Poisson Grillé & Légumes',
    description: 'Filet de tilapia grillé aux herbes de Provence, accompagné de légumes rôtis et sauce vierge.',
    price: 8.75,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot', 'gluten-free'], allergyIds: [],
    available: true, popular: false, isNew: true, calories: 390,
    availableDays: ['Jeudi'],
  },

  // Vendredi
  {
    id: 'm-6',
    name: 'Riz Pilaf Végétarien',
    description: 'Riz basmati parfumé aux épices douces, pois chiches, poivrons colorés et herbes fraîches.',
    price: 6.00,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot', 'vegetarian', 'vegan', 'gluten-free'], allergyIds: [],
    available: true, popular: false, isNew: true, calories: 390,
    availableDays: ['Vendredi'],
  },
  {
    id: 'm-21',
    name: 'Macaroni au Fromage',
    description: 'Macaronis crémeux gratinés au four, mélange de fromages cheddar et gruyère fondu, croûte dorée.',
    price: 6.25,
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot', 'vegetarian'], allergyIds: ['a-1', 'a-2'],
    available: true, popular: true, isNew: false, calories: 490,
    availableDays: ['Vendredi'],
  },
  {
    id: 'm-22',
    name: 'Chili con Carne',
    description: 'Chili texan aux haricots rouges, bœuf haché épicé, tomates concassées et crème fraîche.',
    price: 7.75,
    image: 'https://images.unsplash.com/photo-1564671165093-20688ff1fffa?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-1', schoolIds: ALL, weekIds: W,
    tags: ['hot'], allergyIds: [],
    available: true, popular: false, isNew: false, calories: 530,
    availableDays: ['Vendredi'],
  },

  // ── Entrées (cat-2) — 2–3 days each ──────────────────────────────────────────
  {
    id: 'm-2',
    name: 'Salade César Fraîche',
    description: 'Laitue romaine croquante, croûtons maison dorés, copeaux de parmesan et sauce César légère.',
    price: 6.25,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-2',
    schoolIds: ALL,
    weekIds: W,
    tags: ['cold', 'vegetarian'],
    allergyIds: ['a-1', 'a-2', 'a-4'],
    available: true,
    popular: false,
    isNew: false,
    calories: 320,
    availableDays: ['Lundi', 'Mardi', 'Mercredi'],
  },
  {
    id: 'm-3',
    name: 'Soupe à la Tomate',
    description: 'Soupe onctueuse aux tomates fraîches et basilic, servie avec une tranche de pain de campagne.',
    price: 5.00,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-2',
    schoolIds: ALL,
    weekIds: W,
    tags: ['hot', 'vegetarian'],
    allergyIds: ['a-1'],
    available: true,
    popular: false,
    isNew: true,
    calories: 210,
    availableDays: ['Mardi', 'Jeudi', 'Vendredi'],
  },

  // ── Desserts (cat-3) — every day ─────────────────────────────────────────────
  {
    id: 'm-7',
    name: 'Yaourt aux Fruits Rouges',
    description: 'Yaourt nature onctueux garni de fraises, framboises et myrtilles fraîches, légèrement sucré.',
    price: 3.25,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-3',
    schoolIds: ALL,
    weekIds: W,
    tags: ['cold', 'vegetarian'],
    allergyIds: ['a-2'],
    available: true,
    popular: false,
    isNew: false,
    calories: 140,
    availableDays: EVERY_DAY,
  },
  {
    id: 'm-8',
    name: 'Mousse au Chocolat',
    description: 'Mousse légère au chocolat noir 70%, préparée avec des œufs frais et sans sucre ajouté.',
    price: 3.75,
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-3',
    schoolIds: ['sch-1', 'sch-3'],
    weekIds: W,
    tags: ['cold', 'vegetarian'],
    allergyIds: ['a-2', 'a-4'],
    available: true,
    popular: true,
    isNew: false,
    calories: 190,
    availableDays: ['Lundi', 'Mercredi', 'Vendredi'], // special treat 3×/week
  },
  {
    id: 'm-10',
    name: 'Salade de Fruits Exotiques',
    description: 'Mélange de mangue, ananas, kiwi et papaye, arrosé d\'un coulis de fruits de la passion.',
    price: 3.50,
    image: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-3',
    schoolIds: ALL,
    weekIds: W,
    tags: ['cold', 'vegetarian', 'vegan', 'gluten-free'],
    allergyIds: [],
    available: true,
    popular: false,
    isNew: true,
    calories: 110,
    availableDays: EVERY_DAY,
  },

  // ── Boissons (cat-4) — every day ─────────────────────────────────────────────
  {
    id: 'm-9',
    name: 'Jus d\'Orange Pressé',
    description: 'Jus d\'oranges fraîchement pressées, sans sucre ajouté, riche en vitamine C.',
    price: 2.50,
    image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-4',
    schoolIds: ALL,
    weekIds: W,
    tags: ['cold', 'vegetarian', 'vegan', 'gluten-free'],
    allergyIds: [],
    available: true,
    popular: false,
    isNew: false,
    calories: 90,
    availableDays: EVERY_DAY,
  },

  // ── Collations (cat-5) — every day ───────────────────────────────────────────
  {
    id: 'm-12',
    name: 'Compote Pomme-Cannelle',
    description: 'Pommes du Québec mijotées à la cannelle et sans sucre ajouté, servies en verrines.',
    price: 2.25,
    image: 'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?auto=format&fit=crop&w=400&h=280',
    categoryId: 'cat-5',
    schoolIds: ALL,
    weekIds: W,
    tags: ['cold', 'vegetarian', 'vegan', 'gluten-free'],
    allergyIds: [],
    available: true,
    popular: false,
    isNew: false,
    calories: 80,
    availableDays: EVERY_DAY,
  },
]
